title: Ábel Ilyés-Kun
# description: "CS Graduate | AI for Music | RWTH Aachen"
description: I am Ábel, a computer science graduate from RWTH Aachen University.
        My academic interests include AI for music generation, natural language processing, and computational neuroscience.
        Beyond my studies, I am passionate about playing the piano and enjoy transcribing recordings from my favorite musicians,
        Brad Mehldau and Chick Corea.
theme: jekyll-theme-cayman
